#pragma once

void test_base(void);
void test_ex00(void);
void test_ex01(void);
void test_ex02(void);
void test_ex03(void);
void test_ex04(void);
void test_ex05(void);
void test_ex06(void);
void test_ex07(void);
void test_ex08(void);
void test_ex09(void);
void test_ex10(void);
void test_ex11(void);
void test_ex12(void);
void test_ex13(void);
void test_ex14(void);
void test_ex15(void);